import = ["/home/thecrawler/.config/alacritty/themes/themes/blood_moon.toml"]

[colors.primary]
background = "#1E1E1E"

[cursor.style]
blinking = "Never"

[font]
size = 12

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
dynamic_title = true

[window.padding]
x = 10
y = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
